In [1]:
# Creates a list containing 5 lists, each of 8 items, all set to 0
w, h = 4, 8;
Matrix = [[0 for x in range(w)] for y in range(h)] 
print(Matrix)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [ ]:
Matrix[0][0] = 1111110
Matrix[1][0] = 1110100
Matrix[1][0] = 1001110
Matrix[1][0] = 1
Matrix[1][0] = 
Matrix[1][0] = 
Matrix[1][0] = 
Matrix[1][0] = 1110100
Matrix[1][0] = 1110100
Matrix[1][0] = 1110100

In [ ]:
Matrix[1][0] = 127
Matrix[1][1] = 116
Matrix[1][2] = 78
Matrix[1][3] = 79
Matrix[1][4] = 104
Matrix[1][5] = 91
Matrix[1][6] = 33
Matrix[1][7] = 12


In [2]:
    import numpy
    M = numpy.zeros((8, 4))
print(M)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
print(126)
print(bin(126))

126
0b1111110


In [4]:
A = [126,116,78,79,104,91,33,12]
B = [31754,26914,12170,12484,21634,16564,2180,290]
#C = bin(A)
C = numpy.zeros(8)
# Matrix = [[0 for x in range(w)] for y in range(h)] 
for x in range(7):
    tmp = bin(A[x])
    print(tmp)
    tmp = tmp.replace("0b","4")
    C[x]=tmp
print(A)
print(C)

0b1111110
0b1110100
0b1001110
0b1001111
0b1101000
0b1011011
0b100001
[126, 116, 78, 79, 104, 91, 33, 12]
[41111110. 41110100. 41001110. 41001111. 41101000. 41011011.  4100001.
        0.]


In [ ]:
miscChromosome = 8
tabMiscChromosome = numpy.zeros(miscChromosome)
populationCnt = 10000
tabPopulation = numpy.zeros(populationCnt)
from random import randint
for x in range(populationCnt):
    tabPopulation[x] = randint(0, 127)
tabBin = numpy.zeros(8)
tabDec = numpy.zeros(8)
tabProc = numpy.zeros(8)


In [ ]:
print("TEST")
import numpy as np
D = np.random.choice(127, 8)

print(D)

In [ ]:
print("Populacja składa się z n punktów przestrzeni poszukiwań X (funkcja rand)")
print("Punkty są zakodowane w postaci ciągów binarnych (funkcja dec2bin)")
print("Macierz chromosomów oznaczamy przez: ch1…..chn")
print("Populację początkową oznaczamy P(0) = {ch(0)1…ch(0)n} ")

In [12]:
import ipywidgets as widgets
tbPopulationCnt = widgets.Text(value='1000', description='populationCnt=' )
tbMaxVariousGenothype = widgets.Text(value='127', description='maxVariousGenothype=' )
tbSelectedGenotypeCnt = widgets.Text(value='8', description='selectedGenotypeCnt=' )
display(tbPopulationCnt)
display(tbMaxVariousGenothype)
display(tbSelectedGenotypeCnt)

Text(value='1000', description='populationCnt=')

Text(value='127', description='maxVariousGenothype=')

Text(value='8', description='selectedGenotypeCnt=')

In [30]:
import numpy as np
print("Populacja składa się z n punktów przestrzeni poszukiwań X (funkcja rand)")
tabDifferentGenotype = np.random.choice(int(tbMaxVariousGenothype.value), int(tbSelectedGenotypeCnt.value))
print(tabDifferentGenotype)
print("Punkty są zakodowane w postaci ciągów binarnych (funkcja dec2bin)")
E = tabToBin(tabDifferentGenotype,8).copy()
print(E)
print("Macierz chromosomów oznaczamy przez: ch1…..chn")
print("Populację początkową oznaczamy P(0) = {ch(0)1…ch(0)n} ")

Populacja składa się z n punktów przestrzeni poszukiwań X (funkcja rand)
[76 77 84 96 64 34 37 19]
Punkty są zakodowane w postaci ciągów binarnych (funkcja dec2bin)
[1001100. 1001101. 1010100. 1100000. 1000000.  100010.  100101.   10011.]
Macierz chromosomów oznaczamy przez: ch1…..chn
Populację początkową oznaczamy P(0) = {ch(0)1…ch(0)n} 


In [22]:
def tabToBin(tab,cnt):
    tab2 = np.zeros(cnt)
    for x in range(cnt):
        tab2[x] = bin(tab[x]).replace("0b","")
#     print(tab)
#     print(tab2)
    return tab2
        

In [23]:

tabToBin(D,8)

array([  11111.,   10110.,  101100.,   11000.,  101111.,       0.,
       1100011.,  100000.])

In [32]:
import random
populationCnt = 10000
tabPopulation = np.zeros(populationCnt)
from random import randint
for x in range(populationCnt):
    tabPopulation[x] = random.choice(tabDifferentGenotype) #randint(0, 127)
    
print(tabDifferentGenotype)    
print(tabPopulation)

d
[76 77 84 96 64 34 37 19]
[34. 37. 96. ... 34. 77. 84.]
